name: dependent jobs

on: push

jobs:
  job_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - run: date
  job_on_windows:
    name: A windows job
    runs-on: windows-latest
    steps:
    - name: First step in windows job
      run: date
  job_on_macos:
    name: A job that runs on Macos
    needs: [job_on_ubuntu, job_on_windows]
    name: A job that runs on Mac after first two jobs
  Final_job:
    needs: job_on_macos
    name: A final job
    steps:
